### ISSUE TITLE
seed data

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-squad-builder#2]
## User Story
As a developer, in order to not have to wait, I would need some seed data

## AC
**Given** a developer navigated to the repo
**Then** they should see 2 files in `db` called `squadLists.json` and `squads.json`, each with multiple key value pairs

### db
-  In `db`, create a 2 files called `squadLists.json`, `squads.json`
- create seed data for each file, using the following keys:
- `squadLists.json`
  ```
  name:
  description:
  squadId:
  uid:
  ```
- `squads.json`
  ```
  name:
  character1Id:
  character2Id:
  character3Id:
  character4Id:
  character5Id:
  description:
  uid:
  ```
- `characters.json`
  ```
  name:
  imageUrl:
  ```

### squadListData
- create the file `src/helpers/data/squadListData.js` which:
  - defines a function `getSquadLists` which takes in a `uid` and int he body creates a `new Promise` that calls `axios.get()` for the seed data from firebase
  - defines a function `getSquads` which takes in the argument `squadListId` and makes an `axios.get` call to get the squads from the specific Squad List
